# Generated by Django 6.0.2 on 2026-02-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='S,M,L,XL', max_length=50),
        ),
    ]
