# Generated by Django 4.2.23 on 2026-02-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchingoutfit',
            old_name='pant',
            new_name='bottom',
        ),
        migrations.AlterField(
            model_name='matchingoutfit',
            name='shirt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_bottoms', to='store.product'),
        ),
    ]
