# Generated by Django 6.0.2 on 2026-02-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_actual_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='productsize',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='productsize',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
