# Generated by Django 4.2.23 on 2026-02-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productsize_height_productsize_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
