# Generated by Django 6.0.2 on 2026-02-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_order_status_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='returns/'),
        ),
    ]
