# Generated by Django 4.2.30 on 2026-09-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_is_exchangeable_product_is_returnable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_exchangeable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_returnable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_womens',
            field=models.BooleanField(default=False),
        ),
    ]
