# Generated by Django 4.2.30 on 2026-09-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_category_is_exchangeable_category_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnPolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_window_days', models.PositiveIntegerField(default=7)),
                ('exchange_window_days', models.PositiveIntegerField(default=7)),
                ('reasons', models.TextField(default='Size Issue, Damaged Product, Do Not Like It, Wrong Item, Other')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
